<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Description>DuckDB Bindings for C#.</Description>
    <PackageReleaseNotes>
Updated to DuckDB v1.4.4
    </PackageReleaseNotes>
    <RootNamespace>DuckDB.NET.Native</RootNamespace>
    <RuntimeIdentifiers>win-x64;linux-x64</RuntimeIdentifiers>
		<!-- Set the duckdb runtime version that will be used -->
    <DuckDbArtifactRoot Condition=" '$(DuckDbArtifactRoot)' == '' ">\\archsrv01\Shared\duckdb-extension\v1.4.4</DuckDbArtifactRoot>
    <SignAssembly>True</SignAssembly>
    <AssemblyOriginatorKeyFile>..\keyPair.snk</AssemblyOriginatorKeyFile>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <PropertyGroup Condition="'$(BuildType)' == 'ManagedOnly' ">
    <Description>$(Description) $(NoNativeText)</Description>
  </PropertyGroup>
  
  <!-- Download and include the native libraries into the NuGet package-->
  <Target Name="DownloadNativeLibs" BeforeTargets="GenerateAdditionalSources" Condition="'$(BuildType)' == 'Full' ">
    <MSBuild Projects="DownloadNativeLibs.targets" Properties="Rid=win-x64;LibUrl=$(DuckDbArtifactRoot)/win-x64.zip" />
    <MSBuild Projects="DownloadNativeLibs.targets" Properties="Rid=linux-x64;LibUrl=$(DuckDbArtifactRoot)/linux-x64.zip" />
  </Target>
  <Target Name="CleanNativeLibs" BeforeTargets="Clean" Condition="'$(BuildType)' == 'Full' ">
    <RemoveDir Directories="obj\runtimes" />
  </Target>
  <ItemGroup Condition="'$(BuildType)' == 'Full' ">
    <None Include="obj\runtimes\**\*.dll;obj\runtimes\**\*.so">
      <Visible>false</Visible>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <Pack>true</Pack>
      <PackagePath>\runtimes</PackagePath>
      <Link>runtimes\%(RecursiveDir)\%(FileName)%(Extension)</Link>
    </None>
  </ItemGroup>
  <ItemGroup Condition="'$(CI)' == 'true'">
    <PackageReference Include="GitVersion.MsBuild" Version="6.4.0" PrivateAssets="all" />
  </ItemGroup>
  <ItemGroup Condition="'$(TargetFramework)' == 'netstandard2.0'">
    <PackageReference Include="System.Runtime.CompilerServices.Unsafe" Version="6.1.0" />
  </ItemGroup>
  <!-- End native lib section -->
</Project>
